### ISSUE TITLE
Code coming soon

### ISSUE THREAD

**Issue by peterdn1** [xieenze/TextSR#1]
Looks very cool.  Was hoping to play with this on the weekend, any chance of populating with the source?

SRGAN model (trained on ICDAR2013_train, ICDAR2015_train, SynthText_HR, 100 epochs): 
404 - for both links.

Thanks, 
Peter

**Comment by WenjiaWang0312** [comment]
Sorry for that. 
Codes and models will be released recently. Please wait for a few days.
Have a nice weekend.

**Comment by deep-practice** [comment]
Nice work

**Comment by WenjiaWang0312** [comment]
> Nice work

Thanks😄
