### ISSUE TITLE
Will the relevant code be released now?Thanks

### ISSUE THREAD

**Issue by wulei2018** [xieenze/TextSR#4]

**Comment by WenjiaWang0312** [comment]
Dear wu:
  We are doing a substantial modification to our work and maybe we will postpone the releasing for one or two months.

**Comment by AlexAndrei98-LI** [comment]
Any updates?

**Comment by WenjiaWang0312** [comment]
> Any updates?

😄New version
https://arxiv.org/abs/2005.03341
