### ISSUE TITLE
When can the code be released?

### ISSUE THREAD

**Issue by kunlaotou** [xieenze/TextSR#5]
I read your paper and I feel that your paper is great. Since I am a newbie, I went to read SRGAN first and did experiments. When can your code be released?thx. ^_^

**Comment by WenjiaWang0312** [comment]
Dear kunlaotou:
We think our work is still too weak. Now we are doing a substantial modification to our work and we will postpone the releasing for one or two months. Our paper would be re-wrote as well.

**Comment by kunlaotou** [comment]
> 
> 
> Dear kunlaotou:
> We think our work is still too weak. Now we are doing a substantial modification to our work and we will postpone the releasing for one or two months. Our paper would be re-wrote as well.

铁汁，那祝你们顺利，我再等等~

**Comment by qiu-pinggaizi** [comment]
大兄弟 你们这个实验结果看起来非常棒呀！ 什么时候可以开源代码呢

**Comment by WenjiaWang0312** [comment]
> 大兄弟 你们这个实验结果看起来非常棒呀！ 什么时候可以开源代码呢

重做中

**Comment by qiu-pinggaizi** [comment]
读完你的paper后 我有两个问题想请教一下：1、在github中，你说使用的图像是大于128*32的图像；但在paper中是smaller，这和前者是冲突的呀，所以想要确认一下下。


2、在获取图像中text中，你使用了crop，想请教一下具体怎么处理的；我这边只是想对text做处理，所以想只提取图像中的text信息，如果可以希望可以有相关代码，感谢。

**Comment by WenjiaWang0312** [comment]
> 读完你的paper后 我有两个问题想请教一下：1、在github中，你说使用的图像是大于128*32的图像；但在paper中是smaller，这和前者是冲突的呀，所以想要确认一下下。 2、在获取图像中text中，你使用了crop，想请教一下具体怎么处理的；我这边只是想对text做处理，所以想只提取图像中的text信息，如果可以希望可以有相关代码，感谢。

1. The 'bigger' images are train set, while the 'smaller' images are used as test set.
2. I have uploaded a script: 'crop_800k.py'. You can use this to crop the Syntxt_800K dataset. Remember to change the params.

**Comment by qiu-pinggaizi** [comment]
OK I have downloaded the .py file, I will have a try, thank you.

发自我的iPhone

------------------ Original ------------------

**Comment by RamanHacks** [comment]
Hi Jason, impressive work! Wanted to know if you will release the code soon? Was working on a similar project that's why I was curious! Thanks!

**Comment by WenjiaWang0312** [comment]
> Hi Jason, impressive work! Wanted to know if you will release the code soon? Was working on a similar project that's why I was curious! Thanks!
New version😄
https://arxiv.org/abs/2005.03341
