### ISSUE TITLE
Can you share all the datasets used for training and testing?

### ISSUE THREAD

**Issue by Peter2447** [xieenze/TextSR#6]
I am a newbie. And I'm interested in your outstanding work. Can you share all the datasets you used for training and testing through BaiduNetdisk or other way?

**Comment by WenjiaWang0312** [comment]
test dataset:   [github](https://github.com/chengzhanzhan/STR)
train set:  [baiduyun](https://pan.baidu.com/s/1BMYb93u4gW_3GJdjBWSCSw#list/path=%2F)-password:wi05

**Comment by Peter2447** [comment]
Thanks a lot. I wish you all the best. Looking forward to your paper and codes.

**Comment by xcc19970423** [comment]
Hello,do you have other formats of this training set? Thank you !
