### ISSUE TITLE
Still coming soon?

### ISSUE THREAD

**Issue by RizhaoCai** [xieenze/TextSR#7]
Still coming soon?
Interesting, the code is yet to be uploaded but there are already 68 stars.
We have too much expectation but hope it really comes soon.

**Comment by xieenze** [comment]
Hi
We have make a lot of modifications and re-submit it. And we are waiting for the comments from the reviewers.
Once we get positive feedback, we will release the code as well as the newly collected dataset.
So you should be patient, I will remove the 'coming soon' and you will not be confused.
