### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by mbayo78** [xieenze/TextSR#8]
The new version of the paper was released about 3 weeks ago. Is there a timeline for code release? Really wanted to play with it and apply it to a few different areas for testing.

**Comment by WenjiaWang0312** [comment]
Coming soon. We are waiting for final review.

**Comment by guwen007** [comment]
> Coming soon. We are waiting for final review.

hi, when will you release the code? I am looking forward it.

**Comment by alighofrani95** [comment]
we are still waiting ...
